name: "check merge status"

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      
      # fix issue with lerna clean installs
      - run: lerna bootstrap --no-ci  
      - run: npm lint 
      - run: npm test
